# TIER: SILVER
# DESCRIPTION: Important data for product analytics and A/B testing.
# Backward compatibility is guaranteed.

owner:
  team: "product-analytics-eng"
  support_channel: "#product-analytics-help"

sla:
  - type: "freshness"
    max_latency_hours: 24
  - type: "incident_response"
    resolution: "2 business days"

schema_evolution:
  backward_compatible: true # Can add fields, but not remove/rename them

fields:
  product_id:
    type: string
    required: true
  product_name:
    type: string
    required: true
  category:
    type: string
    required: false
  stock_count:
    type: integer
    required: true

quality_rules:
  - name: "stock_count_is_not_negative"
    expression: "stock_count >= 0"